#include <SchmixEngine/Core/Reflection/ClassDB_CT.h>
#include <SchmixEngine/Core/Reflection/Macros.h>
#include <SchmixEngine/Core/Reflection/Value.h>

namespace SchmixEngine
{
	SMX_BEGIN_REGISTER_CLASS_CT(uint8_t)
	SMX_END_REGISTER_CLASS_CT
	SMX_REGISTER_VALUE_TYPE_FOR_CLASS_CT(uint8_t)

	SMX_BEGIN_REGISTER_CLASS_CT(uint16_t)
	SMX_END_REGISTER_CLASS_CT
	SMX_REGISTER_VALUE_TYPE_FOR_CLASS_CT(uint16_t)

	SMX_BEGIN_REGISTER_CLASS_CT(uint32_t)
	SMX_END_REGISTER_CLASS_CT
	SMX_REGISTER_VALUE_TYPE_FOR_CLASS_CT(uint32_t)

	SMX_BEGIN_REGISTER_CLASS_CT(uint64_t)
	SMX_END_REGISTER_CLASS_CT
	SMX_REGISTER_VALUE_TYPE_FOR_CLASS_CT(uint64_t)

	SMX_BEGIN_REGISTER_CLASS_CT(int8_t)
	SMX_END_REGISTER_CLASS_CT
	SMX_REGISTER_VALUE_TYPE_FOR_CLASS_CT(int8_t)

	SMX_BEGIN_REGISTER_CLASS_CT(int16_t)
	SMX_END_REGISTER_CLASS_CT
	SMX_REGISTER_VALUE_TYPE_FOR_CLASS_CT(int16_t)

	SMX_BEGIN_REGISTER_CLASS_CT(int32_t)
	SMX_END_REGISTER_CLASS_CT
	SMX_REGISTER_VALUE_TYPE_FOR_CLASS_CT(int32_t)

	SMX_BEGIN_REGISTER_CLASS_CT(int64_t)
	SMX_END_REGISTER_CLASS_CT
	SMX_REGISTER_VALUE_TYPE_FOR_CLASS_CT(int64_t)

	SMX_BEGIN_REGISTER_CLASS_CT(float)
	SMX_END_REGISTER_CLASS_CT
	SMX_REGISTER_VALUE_TYPE_FOR_CLASS_CT(float)

	SMX_BEGIN_REGISTER_CLASS_CT(double)
	SMX_END_REGISTER_CLASS_CT
	SMX_REGISTER_VALUE_TYPE_FOR_CLASS_CT(double)

	SMX_BEGIN_REGISTER_CLASS_CT(std::string)
	SMX_END_REGISTER_CLASS_CT
	SMX_REGISTER_VALUE_TYPE_FOR_CLASS_CT(std::string)
}
